window.MACYAESU_CONFIG = {
  sellerName: "MacYaesu",
  sellerCallsign: "",
  siteUrl: "https://www.aiscom.ch/macyaesu/",
  companyName: "MacYaesu",
  priceChf: 49,
  currency: "CHF",
  paypalMerchantEmail: "metacube@gmail.com",
  paypalEndpoint: "https://www.paypal.com/cgi-bin/webscr",
  productName: "MacYaesu Vollversion",
  productNumber: "MACYAESU-1.1",
  supportEmail: "metacube@gmail.com",
  licenseEmail: "metacube@gmail.com",
  pricingEmail: "metacube@gmail.com",
  downloadFile: "./MacYaesu.dmg",
  downloadFileName: "MacYaesu.dmg",
  demoMinutes: 15,
  releaseVersion: "1.1",
  releaseBuild: "2",
  releaseUpdated: "15.08.2026",
  releaseSize: "3.0 MB",
  updatesIncludedTextDe: "Regelmässige Updates sind kostenlos enthalten.",
  updatesIncludedTextEn: "Regular updates are included at no extra cost."
};
