using MudBlazor;

namespace TrafagSalesExporter.Services;

public static class NavigationIconResolver
{
    public static string Resolve(string icon) => icon switch
    {
        "AccountTree" => Icons.Material.Filled.AccountTree,
        "AdminPanelSettings" => Icons.Material.Filled.AdminPanelSettings,
        "Analytics" => Icons.Material.Filled.Analytics,
        "Assignment" => Icons.Material.Filled.Assignment,
        "AssignmentReturn" => Icons.Material.Filled.AssignmentReturn,
        "Checklist" => Icons.Material.Filled.Checklist,
        "CompareArrows" => Icons.Material.Filled.CompareArrows,
        "Dashboard" => Icons.Material.Filled.Dashboard,
        "FactCheck" => Icons.Material.Filled.FactCheck,
        "Sensors" => Icons.Material.Filled.Sensors,
        "Lan" => Icons.Material.Filled.Lan,
        "Timeline" => Icons.Material.Filled.Timeline,
        "Security" => Icons.Material.Filled.Security,
        "Wifi" => Icons.Material.Filled.Wifi,
        "Domain" => Icons.Material.Filled.Domain,
        "SyncAlt" => Icons.Material.Filled.SyncAlt,
        "Policy" => Icons.Material.Filled.Policy,
        "Dns" => Icons.Material.Filled.Dns,
        "History" => Icons.Material.Filled.History,
        "MoveUp" => Icons.Material.Filled.MoveUp,
        "Summarize" => Icons.Material.Filled.Summarize,
        "Storefront" => Icons.Material.Filled.Storefront,
        "Insights" => Icons.Material.Filled.Insights,
        "TrendingDown" => Icons.Material.Filled.TrendingDown,
        "SwapVert" => Icons.Material.Filled.SwapVert,
        "JoinInner" => Icons.Material.Filled.JoinInner,
        "PriceChange" => Icons.Material.Filled.PriceChange,
        "Groups" => Icons.Material.Filled.Groups,
        "Hub" => Icons.Material.Filled.Hub,
        "InsertChart" => Icons.Material.Filled.InsertChart,
        "Inventory" => Icons.Material.Filled.Inventory,
        "Lightbulb" => Icons.Material.Filled.Lightbulb,
        "List" => Icons.Material.Filled.List,
        "LocalShipping" => Icons.Material.Filled.LocalShipping,
        "LocationOn" => Icons.Material.Filled.LocationOn,
        "Lock" => Icons.Material.Filled.Lock,
        "Payments" => Icons.Material.Filled.Payments,
        "PeopleAlt" => Icons.Material.Filled.PeopleAlt,
        "PendingActions" => Icons.Material.Filled.PendingActions,
        "PlaylistAddCheck" => Icons.Material.Filled.PlaylistAddCheck,
        "PieChart" => Icons.Material.Filled.PieChart,
        "Public" => Icons.Material.Filled.Public,
        "QueryStats" => Icons.Material.Filled.QueryStats,
        "Rule" => Icons.Material.Filled.Rule,
        "School" => Icons.Material.Filled.School,
        "Settings" => Icons.Material.Filled.Settings,
        "ShoppingCart" => Icons.Material.Filled.ShoppingCart,
        "Speed" => Icons.Material.Filled.Speed,
        "Storage" => Icons.Material.Filled.Storage,
        "TableChart" => Icons.Material.Filled.TableChart,
        "TableView" => Icons.Material.Filled.TableView,
        "Transform" => Icons.Material.Filled.Transform,
        "TrendingUp" => Icons.Material.Filled.TrendingUp,
        "Tune" => Icons.Material.Filled.Tune,
        "UploadFile" => Icons.Material.Filled.UploadFile,
        "Verified" => Icons.Material.Filled.Verified,
        "EventAvailable" => Icons.Material.Filled.EventAvailable,
        "ViewInAr" => Icons.Material.Filled.ViewInAr,
        "WarningAmber" => Icons.Material.Filled.WarningAmber,
        "TravelExplore" => Icons.Material.Filled.TravelExplore,
        "AutoAwesome" => Icons.Material.Filled.AutoAwesome,
        "Radar" => Icons.Material.Filled.Radar,
        "ShowChart" => Icons.Material.Filled.ShowChart,
        "Feed" => Icons.Material.Filled.Feed,
        _ => Icons.Material.Filled.Circle
    };
}
