namespace TrafagSalesExporter.Services;

/// <summary>
/// Reviewed Klingon paraphrases for the dynamic purchasing catalogue. Product,
/// SAP and currency identifiers remain unchanged; missing business terms are
/// expressed with existing Klingon words instead of English loan words.
/// </summary>
internal static class PurchasingKlingonOverrides
{
    internal static readonly IReadOnlyDictionary<string, string> All =
        new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["Einkauf Cache Vollwerte"] = "je'meH De' polDaq De' naQ",
            ["EKKO live, Positionswerte fehlen noch"] = "DaH EKKO De' tu'lu'; Dochmey Huch De' Hutlh",
            ["EKKO-Belege im Zeitraum"] = "poHvam EKKO je'meH ra'mey",
            ["Einkaufsbelege sind im Zeitraum"] = "poHvam De' HaStaDaq je'meH ra'mey tu'lu'",
            ["EKKO im Zeitraum"] = "poHvam EKKO",
            ["Noch nicht geladen"] = "wej De' qemlu'",
            ["offener Bestell-/Abrufwert Stand heute, zeitraumunabhaengig"] = "DaHjaj je'meH ra'mey rInbe'bogh Huch; poH wIvbe'lu'",
            ["Restwert aus EKET/EKPO-Sample"] = "EKET/EKPO De' machvo' Huch puch",
            ["EKKO live, Terminwerte fehlen noch"] = "DaH EKKO De' tu'lu'; poH Huch De' Hutlh",
            ["aktive Lieferanten mit Spend-Positionen"] = "ngevwI'pu' vum 'ej Huch lo'bogh Dochmey",
            ["Zeitfilter und Verlauf"] = "poH nej 'ej choH legh",
            ["Spend und Performance pro Lieferant"] = "ngevwI' Hoch Huch lo' Qapchu'ghach je",
            ["Spend nach Warengruppe"] = "Hap ghom Hoch Huch lo'",
            ["Artikel- und Preisentwicklung"] = "Doch Huch choH je",
            ["Regionale Spend-Verteilung"] = "mIchmeyDaq Huch lo' wav",
            ["Bestellkopf wartet auf SAP"] = "je'meH ra' nachvaD SAP loSlu'",
            ["Anzahl Bestellpositionen im Zeitraum"] = "poHvam je'meH Dochmey mI'",
            ["Spend und offene Werte bleiben Simulation"] = "Huch lo' rInbe'bogh Huch je ngeb De' neH",
            ["Anzahl Termineinteilungen im Zeitraum"] = "poHvam poH nab tlheghmey mI'",
            ["Faelligkeiten und Kontrakte warten auf SAP"] = "rInmeH poHmey mabmey je SAP loS",
            ["Livewerte, Simulation und 3D-Analyse werden getrennt ausgewiesen"] = "DaH De', ngeb De', wej-D poj je pImmoHlu'",
            ["aus SAP Positionen"] = "SAP Dochmeyvo'",
            ["Simulation bis EKPO liefert"] = "EKPO De' pawpa' ngeb De' lo'lu'",
            ["Matrix wie Excel/PowerBI"] = "Excel Power BI rur De' tlheghmey",
            ["Jahr, Lieferant, Warengruppe, Artikel"] = "DIS, ngevwI', Hap ghom, Doch",
            ["EKPOSet fuer Spend notwendig"] = "EKPOSet poQlu'",
            ["mit nicht geloeschten Positionen"] = "polHa'lu'be'bogh Dochmey ghaj",
            ["aus SAP Terminen/Positionen"] = "SAP poH nabmey Dochmey jevo'",
            ["Simulation bis EKET liefert"] = "EKET De' pawpa' ngeb De' lo'lu'",
            ["aus SAP Terminen"] = "SAP poH nabmeyvo'",
            ["aus SAP Einteilungen"] = "SAP poH nabmeyvo'",
            ["EKET-Probe"] = "EKET De' mach",
            ["Lieferant / Artikel / Monat"] = "ngevwI' / Doch / jar",
            ["letztes bekanntes EKKO-Datum"] = "EKKO jaj Qav Sovlu'bogh",
            ["mit nicht geloeschten EKPO-Positionen"] = "polHa'lu'be'bogh EKPO Dochmey ghaj",
            ["Simulation bis Bewertungsdaten kommen"] = "nuDmeH De' pawpa' ngeb De' lo'lu'",
            ["Netwr CHF/Stk braucht EKPO"] = "Doch Hoch CHF HuchvaD EKPO poQlu'",
            ["Reklamationsquelle noch nicht angebunden"] = "DoQ Hal wej rar",
            ["berechenbar"] = "SImlaH",
            ["wartet auf EKPO/EKET"] = "EKPO/EKET loS",
            ["teilweise"] = "'ay' neH",
            ["wartet auf EKET"] = "EKET loS",
            ["wartet auf EKPO"] = "EKPO loS",
            ["Wartet auf SAP"] = "SAP loS",
            ["als Detail verfuegbar"] = "De' le' tu'lu'",
            ["offener Wert"] = "Huch rInbe'",
            ["kurzfristig faellig"] = "tugh rInmeH poH",
            ["offene Mengen"] = "mI' rInbe'",
            ["Top nach Spend"] = "Huch lo' law' law'",
            ["> +2% ggue. Vorjahr"] = "> +2 vatlhvI'; DIS nungbogh juS",
            ["Lieferanten-Pareto"] = "ngevwI'pu' Huch lo' patlh",
            ["vom Gesamtspend"] = "Huch lo' Hochvo'",
            ["Spend netto"] = "Huch lo' teH",
            ["Pflichtfelder"] = "yotlhmey poQlu'bogh",
            ["Cache-Zeilen"] = "De' polDaq tlheghmey",
            ["Positionen"] = "Dochmey",
            ["Bestellkoepfe"] = "je'meH ra' nachmey",
            ["Liefertermin-Risiko produktiv"] = "Qapbogh ngevmeH poH Qob poj",
            ["Preisentwicklung CHF produktiv"] = "Qapbogh CHF Huch choH poj",
            ["Spend-Konzentration produktiv"] = "Qapbogh Huch lo' qev poj",
            ["Datenqualitaet produktiv"] = "Qapbogh De' QaQghach poj",
            ["Einkauf Analyse"] = "je'meH poj",
            ["Offene EKET-Mengen werden bewertet und nach Faelligkeit, Lieferant und Artikel priorisiert."] = "EKET mI' rInbe' Huch SImlu'; rInmeH poH, ngevwI' Doch je lo'lu' potlh patlh chermeH.",
            ["Netto-Stueckpreise werden wie in PowerBI als Minimum je Artikel und Jahr gezeigt."] = "Power BI rur; Doch Hoch DIS Hoch Huch machqu' 'anglu'.",
            ["Lieferantenspend wird als Pareto ausgewertet, um Abhaengigkeit und Buendelungspotenzial zu zeigen."] = "ngevwI' Huch lo' patlh pojlu'; wa' ngevwI' wuvlu'ghach je Huch lo' ghomlaHghach je 'anglu'.",
            ["Pflichtfelder und Nullwerte im Einkauf-Cache werden als Qualitaetsampel gezaehlt."] = "je'meH De' polDaq yotlhmey poQlu'bogh pagh Huchmey je toblu'; De' QaQghach 'anglu'.",
            ["Echte Analyse aus dem Einkauf-Cache."] = "je'meH De' polDaqvo' poj teH.",
            ["Offener Wert nach Faelligkeit"] = "rInmeH poH Hoch Huch rInbe'",
            ["Min. Stueckpreis nach Jahr"] = "DIS Hoch Doch Huch machqu'",
            ["Top Lieferanten Spend"] = "ngevwI' Huch lo' law' law'",
            ["Datenqualitaetsfehler"] = "De' QaQghach Qaghmey",
            ["Beschaffungsregion"] = "je'meH mIch",
            ["Waehrung"] = "Huch Segh",
            ["Material"] = "Hap",
            ["Waehrung des Bestellbelegs (EKKO-Waers). Balken und erster Betrag sind nach CHF bewertet, damit die Waehrungen vergleichbar sind; in Klammern die Summe in der Belegwaehrung selbst (das tatsaechliche Waehrungsexposure). NICHT die Beschaffungsregion: ein Schweizer Lieferant kann in EUR fakturieren."] = "je'meH ra' Huch Segh 'oH EKKO-Waers'e'. Huch Seghmey rapmoHmeH, naQmey mI' wa'DIch je CHF lo'lu' SImmeH; qIvDaq ra' Huch Segh mI' Hoch 'anglu'. je'meH mIch 'oHbe'; EUR Huch nav chenmoHlaH ngevwI'.",
            ["Beschaffungsregion = Land des Lieferanten (LFA1-Land1), ueber den Bestellbeleg zugeordnet. Zeigt den CHF-Spend je Lieferantenland im gewaehlten Zeitraum."] = "je'meH mIch 'oH ngevwI' Sep'e' (LFA1-Land1); je'meH ra' lo'lu' rarmeH. poH wIvlu'bogh ngevwI' Sep Hoch CHF Huch lo' 'anglu'.",
            ["Warengruppe aus dem Materialstamm (MARA-MATKL), Fallback Beleg-Warengruppe (EKPO.Matkl). Texte aus dem SAP-Export T023T; unbekannte Codes zeigen den reinen Code. \"01\" ist die SAP-Sammelgruppe \"Dummy\" fuer unklassifizierte Altbestaende."] = "Hap wa'DIch De'vo' Hap ghom Suqlu' (MARA-MATKL); Hutlhchugh ra' Hap ghom lo'lu' (EKPO.Matkl). SAP T023T De' ngeHvo' pongmey Suqlu'; ngoq Sovbe'lu'boghvaD ngoq neH 'anglu'. \"01\" 'oH SAP Hapmey Seghbe'lu'bogh ghom'e'."
        };
}
