namespace TrafagSalesExporter.Services;

/// <summary>
/// German/English source pairs that the purchasing UI selects dynamically.
/// Literal T(de, en) calls are covered by the general generated catalogue;
/// this inventory closes the gap for conditional values and parallel switch
/// expressions that cannot be discovered reliably with a source regex.
/// </summary>
internal static class PurchasingUiTextCatalog
{
    // SAP field help introduced 2026-09-10 is authored in German/English.
    // Explicit English fallbacks for other languages preserve the technical meaning
    // until reviewed translations are available. These are not translated texts.
    internal static readonly IReadOnlyList<(string German, string English)> FieldHelpEnglishFallbacks =
    [
        ("Bestellwerte, Lieferanten und offene Liefermengen", "Ordered values, suppliers and open delivery quantities"),
        ("Bestellungen, offene Liefermengen und Lagerwerte aus SAP. Die Quellenhilfe erklaert die Kennzahlen und nennt die SAP-Felder.", "Purchase orders, open delivery quantities and stock values from SAP. The source guide explains the measures and identifies their SAP fields."),
        ("Geladen", "Loaded"),
        ("Bestellwerte und Lieferantenzahl nach Bestelldatum (EKKO.BEDAT). Offene Werte enthalten alle Jahre; der Lagerwert zeigt seinen eigenen Ladestand.", "Ordered values and supplier count use the order date (EKKO.BEDAT). Open values include all years; stock value has its own load timestamp."),
        ("Datenstatus wird geladen.", "Loading data status."),
        ("Quelle: gespeicherte SAP-Daten, keine Echtzeitabfrage. Letzter protokollierter Ladelauf:", "Source: stored SAP data, not a real-time query. Last recorded load:"),
        ("Ein fehlgeschlagener oder laufender Ladelauf bestaetigt keinen neuen Datenstand. Der Lagerwert hat einen eigenen Zeitstempel an der Kachel.", "A failed or running load does not confirm a new data snapshot. Stock value has its own timestamp on the card."),
        ("Ohne gespeicherten Bestand: begrenzte SAP-Stichprobe, sofern erreichbar. Stichproben und gekennzeichnete Simulationen sind keine vollstaendigen Einkaufswerte.", "Without stored data: a limited SAP sample, if reachable. Samples and labelled simulations are not complete purchasing totals."),
        ("Kennzahlen verstehen: SAP-Quellen und Felder", "Understanding measures: SAP sources and fields"),
        ("Die Formeln beschreiben den gespeicherten Einkaufsbestand. Bestellkopf EKKO und Position EKPO sind ueber EBELN verbunden; Einteilungen EKET ueber EBELN und EBELP. Die SAP-Feldnamen bleiben zum Nachschlagen unveraendert.", "The formulas describe the stored purchasing data. Order header EKKO and item EKPO join on EBELN; schedule lines EKET join on EBELN and EBELP. SAP field names are preserved for reference."),
        ("Kennzahl / Feld", "Measure / field"),
        ("Herkunft und Berechnung", "Source and calculation"),
        ("Bestellwert / Jahr", "Ordered value / year"),
        ("Summe EKPO.NETWR (Netto-Positionswert), in CHF umgerechnet. Zeitraum und Jahr aus EKKO.BEDAT (Bestelldatum). Kein Rechnungs- oder Zahlungswert.", "Sum of EKPO.NETWR (net item value), converted to CHF. Period and year from EKKO.BEDAT (order date). Not an invoice or payment value."),
        ("Bestellungen / Lieferanten", "Orders / suppliers"),
        ("Unterschiedliche EKKO.EBELN (Bestellnummern) mit passenden Positionen; Lieferanten als unterschiedliche EKKO.LIFNR mit EKPO.NETWR ungleich 0 im Zeitraum. Keine Lieferantenbewertung.", "Distinct EKKO.EBELN (order numbers) with matching items; suppliers are distinct EKKO.LIFNR with non-zero EKPO.NETWR in the period. Not a supplier rating."),
        ("Offene Menge / offener Bestellwert", "Open quantity / order value"),
        ("Je Einteilung: MAX(EKET.MENGE - EKET.WEMNG, 0), also eingeplante Menge minus erfasste Wareneingangsmenge. Wert = offene Menge × (EKPO.NETWR in CHF / EKPO.MENGE). Bei Bestellmenge 0 ist der Stueckwert 0. Alle Jahre inklusive alter Rueckstaende.", "Per schedule line: MAX(EKET.MENGE - EKET.WEMNG, 0), scheduled quantity minus recorded received quantity. Value = open quantity × (EKPO.NETWR in CHF / EKPO.MENGE). A zero order quantity gives a zero unit value. All years, including old backlogs."),
        ("Ueberfaelliger Wert / Positionen", "Overdue value / items"),
        ("Offener Bestellwert mit EKET.EINDT (geplanter Liefertermin) vor heute. Positionszahl zaehlt unterschiedliche EBELN/EBELP mit offener ueberfaelliger Einteilung. EKET.EINDT ist kein tatsaechliches Wareneingangsdatum; daraus wird keine Liefertreue berechnet.", "Open order value with EKET.EINDT (planned delivery date) before today. Item count uses distinct EBELN/EBELP with an overdue open schedule line. EKET.EINDT is not an actual receipt date; it does not measure delivery reliability."),
        ("Offener Wert der Kontraktabrufe", "Open contract call-off value"),
        ("Gleiche Offenwert-Formel, eingeschraenkt auf Bestellungen mit gefuelltem EKKO.KONNR (Kontraktbezug). Naeherung fuer offene Abrufe, kein noch verfuegbarer Vertragsrahmen. Ohne KONNR-Zuordnung ergibt sich 0.", "Same open-value formula, restricted to orders with EKKO.KONNR (contract reference). An approximation of open call-offs, not unused contract capacity. No KONNR assignments results in 0."),
        ("Waehrung / CHF-Umrechnung", "Currency / CHF conversion"),
        ("EKKO.WAERS ist die Belegwaehrung; EKKO.WKURS der Kurs des Bestellbelegs. Positiver Kurs: multiplizieren; negativer Kurs: durch den Absolutwert teilen. CHF bleibt unveraendert. Bei fehlender Waehrung oder Kurs 0 bleibt der Betrag derzeit ebenfalls unveraendert. Der Waehrungsaufriss gruppiert nach Belegwaehrung und zeigt CHF-Werte.", "EKKO.WAERS is the document currency; EKKO.WKURS the order document exchange rate. Positive rate: multiply; negative rate: divide by its absolute value. CHF is unchanged. Missing currency or a zero rate currently also leaves the amount unchanged. The currency breakdown groups by document currency and shows CHF values."),
        ("Lieferant / Material / Warengruppe", "Supplier / material / material group"),
        ("Lieferant: EKKO.LIFNR → LFA1.NAME1; Land: LFA1.LAND1. Material: EKPO.MATNR mit MAKT.MAKTX im Drilldown. Ohne Stammtext bleibt die Nummer; ohne Materialnummer wird EKPO.TXZ01 angezeigt. Warengruppe: MARA.MATKL, ersatzweise EKPO.MATKL; Texte aus dem lokalen T023T-Katalog.", "Supplier: EKKO.LIFNR → LFA1.NAME1; country: LFA1.LAND1. Material: EKPO.MATNR with MAKT.MAKTX in the drilldown. Missing master text leaves the number; without a material number, EKPO.TXZ01 is shown. Material group: MARA.MATKL, falling back to EKPO.MATKL; descriptions from the local T023T catalogue."),
        ("Summe MBEW.SALK3 (bewerteter Gesamtbestand), Bewertungskreis MBEW.BWKEY = 1100; Zuordnung ueber Materialnummer zu MARC.DISPO, Disponenten 001–005. Eigener gespeicherter Abrufzeitpunkt an der Kachel; unabhaengig vom Bestellzeitraum.", "Sum of MBEW.SALK3 (valued total stock), valuation area MBEW.BWKEY = 1100; material number maps to MARC.DISPO, planners 001–005. Its own stored retrieval timestamp is shown on the card; independent of the order period."),
        ("Beleg- und Positionsfilter", "Document and item filters"),
        ("Standard: EKKO.BSTYP = F (Bestellung), EKKO.BSART ungleich UB (keine Umlagerung). Der Storno-Schalter schliesst EKPO.LOEKZ aus; bei offenen Werten zusaetzlich MARA.MSTAE 98/99. Endgelieferte Positionen (EKPO.ELIKZ = X) sind aus offenen Werten ausgeschlossen.", "Default: EKKO.BSTYP = F (purchase order), EKKO.BSART other than UB (no stock transfers). The cancellation filter excludes EKPO.LOEKZ; open values also exclude MARA.MSTAE 98/99. Delivery-completed items (EKPO.ELIKZ = X) are excluded from open values."),
        ("SAP-Datenbestand", "Stored SAP data"),
        ("SAP-Stichprobe", "SAP sample"),
        ("Nicht berechnet: Ist-Wareneingangsdatum fehlt", "Not calculated: actual receipt date missing"),
        ("Bestellwert aus EKPO.NETWR in CHF, Zeitraum nach EKKO.BEDAT, Umrechnung mit EKKO.WAERS/WKURS. Perspektive waehlen und aufklappen: alle Lieferanten, Warengruppen und Materialien bleiben sichtbar. Warengruppe aus MARA.MATKL, ersatzweise EKPO.MATKL. In der Waehrungssicht ist die Gruppe die Belegwaehrung, der Wert bleibt CHF.", "Ordered value from EKPO.NETWR in CHF, period from EKKO.BEDAT, conversion using EKKO.WAERS/WKURS. Select a perspective and expand: all suppliers, material groups and materials remain visible. Material group from MARA.MATKL, falling back to EKPO.MATKL. Currency groups represent document currency; values remain CHF."),
        ("Gespeicherte SAP-Einkaufsdaten", "Stored SAP purchasing data"),
        ("Ordered value by supplier and year", "Ordered value by supplier and year"),
        ("What is ordered and not yet here: open quantity per schedule line times unit value. Deliberately period-independent, across all years in the loaded SAP data so old backlogs do not disappear. Includes old backlogs still open in SAP. Purchase orders only, no quantity contracts.", "What is ordered and not yet here: open quantity per schedule line times unit value. Deliberately period-independent, across all years in the loaded SAP data so old backlogs do not disappear. Includes old backlogs still open in SAP. Purchase orders only, no quantity contracts."),
        ("Open contract call-offs", "Open contract call-offs"),
        ("Suppliers and order prices", "Suppliers and order prices"),
        ("Suppliers from EKKO.LIFNR with EKPO order items, names from LFA1.NAME1. Order prices from EKPO.NETWR / EKPO.MENGE in CHF. Delivery reliability and quality are not rated because actual receipt and claim data are not connected.", "Suppliers from EKKO.LIFNR with EKPO order items, names from LFA1.NAME1. Order prices from EKPO.NETWR / EKPO.MENGE in CHF. Delivery reliability and quality are not rated because actual receipt and claim data are not connected."),
        ("SAP: EKPO.NETWR, EKKO.BEDAT, EKKO.WAERS/WKURS. Bestelltes Volumen am Bestelldatum, nicht Wareneingang und nicht Rechnung. Nur echte Bestellungen, umgerechnet mit dem Kurs vom Bestellbeleg.", "SAP: EKPO.NETWR, EKKO.BEDAT, EKKO.WAERS/WKURS. Ordered volume on the order date, not goods receipt and not invoice. Purchase orders only, converted with the rate fixed on the order document."),
        ("SAP: EKKO.EBELN und EKKO.BEDAT. Anzahl Bestellbelege im Zeitraum, gezaehlt am Bestelldatum. Ein Beleg mit zwanzig Positionen zaehlt einmal.", "SAP: EKKO.EBELN and EKKO.BEDAT. Number of order documents in the period, counted on the order date. A document with twenty items counts once."),
        ("Offener Bestellwert inkl. Rueckstaende", "Open order value incl. backlog"),
        ("SAP: EKET.MENGE/WEMNG, EKPO.NETWR/MENGE, EKKO.WAERS/WKURS. Bestellt und noch nicht eingetroffen: offene Menge mal Stueckwert, laut geladenem SAP-Stand ueber alle Jahre. Enthaelt auch alte, nie geschlossene Einteilungen; nur Bestellungen, keine Mengenkontrakte.", "SAP: EKET.MENGE/WEMNG, EKPO.NETWR/MENGE, EKKO.WAERS/WKURS. Ordered and not yet arrived: open quantity times unit value, across all years in the loaded SAP data. Includes old schedule lines never closed; purchase orders only, no quantity contracts."),
        ("Aktive Lieferanten im Zeitraum", "Active suppliers in period"),
        ("SAP: EKKO.LIFNR, EKPO.NETWR, EKKO.BEDAT; Name aus LFA1.NAME1. Anzahl Lieferanten mit mindestens einer Bestellposition ungleich null im Zeitraum. Sagt nichts ueber Liefertreue oder Qualitaet aus.", "SAP: EKKO.LIFNR, EKPO.NETWR, EKKO.BEDAT; name from LFA1.NAME1. Number of suppliers with at least one non-zero order item in the period. Says nothing about delivery reliability or quality."),
        ("SAP: MBEW.SALK3 (Bestandswert), MBEW.BWKEY (Bewertungskreis), MARC.DISPO (Disponent). Bewerteter Lagerbestand zum letzten erfolgreichen Lagerwert-Abruf, eine Stichtagsbetrachtung. Ein frei waehlbarer Stichtag ist nicht moeglich, die Quelle fuehrt nur den Jetzt-Wert.", "SAP: MBEW.SALK3 (stock value), MBEW.BWKEY (valuation area), MARC.DISPO (planner). Valued stock at the last successful stock value load, a snapshot. A freely chosen key date is not possible, the source only carries the current value."),
        ("EKKO.LIFNR → LFA1.NAME1", "EKKO.LIFNR → LFA1.NAME1"),
        ("MARA.MATKL / EKPO.MATKL; T023T-Textkatalog", "MARA.MATKL / EKPO.MATKL; T023T-Textkatalog"),
        ("EKPO.MATNR + MAKT.MAKTX; ohne MATNR: EKPO.TXZ01", "EKPO.MATNR + MAKT.MAKTX; ohne MATNR: EKPO.TXZ01"),
        ("LFA1.LAND1", "LFA1.LAND1"),
        ("LFA1Set", "LFA1Set"),
        ("maracalcSet", "maracalcSet"),
        ("Einteilungen im Zeitraum (alle Belege)", "Schedule lines in period (all documents)"),
        ("Lieferantennamen werden aus LFA1.NAME1 ueber EKKO.LIFNR geladen.", "Supplier names are loaded from LFA1.NAME1 via EKKO.LIFNR."),
        ("Open contract call-off value", "Open contract call-off value"),
        ("Bestellpositionen mit Kontraktbezug", "Order items with contract reference"),
    ];

    internal static readonly IReadOnlyList<(string German, string English)> All =
    [
        ("Einkauf Cache Vollwerte", "purchasing cache full values"),
        ("EKKO live, Positionswerte fehlen noch", "EKKO live, position values still missing"),
        ("EKKO-Belege im Zeitraum", "EKKO orders in period"),
        ("Einkaufsbelege sind im Zeitraum", "purchase orders are in the cockpit for"),
        ("EKKO im Zeitraum", "EKKO in period"),
        ("Noch nicht geladen", "Not loaded yet"),
        ("offener Bestell-/Abrufwert Stand heute, zeitraumunabhaengig", "open order/call-off value as of today, period-independent"),
        ("Restwert aus EKET/EKPO-Sample", "remaining value from EKET/EKPO sample"),
        ("EKKO live, Terminwerte fehlen noch", "EKKO live, schedule values still missing"),
        ("aktive Lieferanten mit Spend-Positionen", "active suppliers with spend items"),
        ("Zeitfilter und Verlauf", "Time filter and trend"),
        ("Spend und Performance pro Lieferant", "Spend and performance by supplier"),
        ("Spend nach Warengruppe", "Spend by material group"),
        ("Artikel- und Preisentwicklung", "Article and price development"),
        ("Regionale Spend-Verteilung", "Regional spend distribution"),
        ("Bestellkopf wartet auf SAP", "Purchase header is waiting for SAP"),
        ("Anzahl Bestellpositionen im Zeitraum", "Number of order items in period"),
        ("Spend und offene Werte bleiben Simulation", "Spend and open values remain simulation"),
        ("Anzahl Termineinteilungen im Zeitraum", "Number of schedule lines in period"),
        ("Faelligkeiten und Kontrakte warten auf SAP", "Due dates and contracts wait for SAP"),
        ("Livewerte, Simulation und 3D-Analyse werden getrennt ausgewiesen", "Live values, simulation and 3D analysis are shown separately"),
        ("aus SAP Positionen", "from SAP item rows"),
        ("Simulation bis EKPO liefert", "simulation until EKPO delivers"),
        ("Matrix wie Excel/PowerBI", "matrix like Excel/Power BI"),
        ("Jahr, Lieferant, Warengruppe, Artikel", "year, supplier, material group, article"),
        ("EKPOSet fuer Spend notwendig", "EKPOSet required for spend"),
        ("mit nicht geloeschten Positionen", "with non-deleted items"),
        ("aus SAP Terminen/Positionen", "from SAP schedules/items"),
        ("Simulation bis EKET liefert", "simulation until EKET delivers"),
        ("aus SAP Terminen", "from SAP schedules"),
        ("aus SAP Einteilungen", "from SAP schedules"),
        ("EKET-Probe", "EKET sample"),
        ("Lieferant / Artikel / Monat", "supplier / article / month"),
        ("letztes bekanntes EKKO-Datum", "latest known EKKO date"),
        ("mit nicht geloeschten EKPO-Positionen", "with non-deleted EKPO items"),
        ("Bewertungsdaten (EKBE/QM) nicht angebunden", "rating data (EKBE/QM) not connected"),
        ("Netwr CHF/Stk braucht EKPO", "Netwr CHF/unit needs EKPO"),
        ("Reklamationsquelle noch nicht angebunden", "claim source not connected yet"),
        ("berechenbar", "calculable"),
        ("wartet auf EKPO/EKET", "waiting for EKPO/EKET"),
        ("teilweise", "partial"),
        ("wartet auf EKET", "waiting for EKET"),
        ("wartet auf EKPO", "waiting for EKPO"),
        ("Wartet auf SAP", "Waiting for SAP"),
        ("als Detail verfuegbar", "available as detail"),
        ("offener Wert", "open value"),
        ("kurzfristig faellig", "due short-term"),
        ("offene Mengen", "open quantities"),
        ("Top nach Spend", "top by spend"),
        ("> +2% ggue. Vorjahr", "> +2% vs. prior year"),
        ("Lieferanten-Pareto", "supplier pareto"),
        ("vom Gesamtspend", "of total spend"),
        ("Spend netto", "net spend"),
        ("Pflichtfelder", "required fields"),
        ("Cache-Zeilen", "cache rows"),
        ("Positionen", "items"),
        ("Bestellkoepfe", "headers"),
        ("Liefertermin-Risiko produktiv", "Delivery due-date risk productive"),
        ("Preisentwicklung CHF produktiv", "Price trend CHF productive"),
        ("Spend-Konzentration produktiv", "Spend concentration productive"),
        ("Datenqualitaet produktiv", "Data quality productive"),
        ("Einkauf Analyse", "Purchasing analysis"),
        ("Offene EKET-Mengen werden bewertet und nach Faelligkeit, Lieferant und Artikel priorisiert.", "Open EKET quantities are valued and prioritised by due date, supplier and article."),
        ("Netto-Stueckpreise werden wie in PowerBI als Minimum je Artikel und Jahr gezeigt.", "Net unit prices are shown like in Power BI as minimum by article and year."),
        ("Lieferantenspend wird als Pareto ausgewertet, um Abhaengigkeit und Buendelungspotenzial zu zeigen.", "Supplier spend is evaluated as pareto to show dependency and bundling potential."),
        ("Pflichtfelder und Nullwerte im Einkauf-Cache werden als Qualitaetsampel gezaehlt.", "Required fields and zero values in the purchasing cache are counted as quality indicators."),
        ("Echte Analyse aus dem Einkauf-Cache.", "Real analysis from the purchasing cache."),
        ("Offener Wert nach Faelligkeit", "Open value by due date"),
        ("Ø Stueckpreis nach Jahr (mengengewichtet)", "Avg. unit price by year (quantity-weighted)"),
        ("Top Lieferanten Spend", "Top supplier spend"),
        ("Datenqualitaetsfehler", "Data quality issues"),
        ("Beschaffungsregion", "Procurement region"),
        ("Waehrung", "Currency"),
        ("Material", "Material"),
        ("Waehrung des Bestellbelegs (EKKO-Waers). Balken und erster Betrag sind nach CHF bewertet, damit die Waehrungen vergleichbar sind; in Klammern die Summe in der Belegwaehrung selbst (das tatsaechliche Waehrungsexposure). NICHT die Beschaffungsregion: ein Schweizer Lieferant kann in EUR fakturieren.", "Currency of the purchase order (EKKO Waers). Bars and the first amount are valued in CHF so the currencies are comparable; in brackets the sum in the document currency itself (the actual currency exposure). NOT the procurement region: a Swiss supplier can invoice in EUR."),
        ("Beschaffungsregion = Land des Lieferanten (LFA1-Land1), ueber den Bestellbeleg zugeordnet. Zeigt den CHF-Spend je Lieferantenland im gewaehlten Zeitraum.", "Procurement region = supplier country (LFA1 Land1), assigned via the purchase order. Shows CHF spend by supplier country in the selected period."),
        ("Warengruppe aus dem Materialstamm (MARA-MATKL), Fallback Beleg-Warengruppe (EKPO.Matkl). Texte aus dem SAP-Export T023T; unbekannte Codes zeigen den reinen Code. \"01\" ist die SAP-Sammelgruppe \"Dummy\" fuer unklassifizierte Altbestaende.", "Material group from the material master (MARA-MATKL), fallback to the document material group (EKPO.Matkl). Texts from the SAP export T023T; unknown codes show the bare code. \"01\" is SAP's catch-all group \"Dummy\" for unclassified legacy stock."),
        ("Stammdaten nachpflegen; ohne beide Klassen ist keine belastbare Beschaffungsstrategie ableitbar.", "Complete master data; without both classes no reliable procurement strategy can be derived."),
        ("Strategisch absichern: Rahmenvertrag, Lieferfaehigkeit und automatische Disposition pruefen.", "Secure strategically: review framework agreement, supply capability and automated planning."),
        ("Versorgungsrisiko priorisieren: Forecast, Sicherheitsbestand und Zweitquelle pruefen.", "Prioritize supply risk: review forecast, safety stock and a second source."),
        ("Standardisieren und Mengen buendeln; Bestellrhythmus und Konditionen optimieren.", "Standardize and bundle volumes; optimize order cadence and terms."),
        ("Losgroessen, Mindestmengen und schwankende Bedarfsursachen mit dem Disponenten pruefen.", "Review lot sizes, minimum quantities and volatile demand drivers with the planner."),
        ("Prozesskosten senken: Katalog, Automatisierung und Sammelbestellungen pruefen.", "Reduce process cost: review catalog, automation and consolidated orders."),
        ("Tail Spend reduzieren: buendeln, auslisten oder auf Standardalternativen umstellen.", "Reduce tail spend: bundle, phase out or switch to standard alternatives."),
        ("Klassifikation fachlich pruefen und anschliessend einer Beschaffungsstrategie zuordnen.", "Validate the classification and then assign a procurement strategy.")
    ];
}
