namespace TrafagSalesExporter.Services;

/// <summary>
/// German/English source pairs that the purchasing UI selects dynamically.
/// Literal T(de, en) calls are covered by the general generated catalogue;
/// this inventory closes the gap for conditional values and parallel switch
/// expressions that cannot be discovered reliably with a source regex.
/// </summary>
internal static class PurchasingUiTextCatalog
{
    internal static readonly IReadOnlyList<(string German, string English)> All =
    [
        ("Einkauf Cache Vollwerte", "purchasing cache full values"),
        ("EKKO live, Positionswerte fehlen noch", "EKKO live, position values still missing"),
        ("EKKO-Belege im Zeitraum", "EKKO orders in period"),
        ("Einkaufsbelege sind im Zeitraum", "purchase orders are in the cockpit for"),
        ("EKKO im Zeitraum", "EKKO in period"),
        ("Noch nicht geladen", "Not loaded yet"),
        ("offener Bestell-/Abrufwert Stand heute, zeitraumunabhaengig", "open order/call-off value as of today, period-independent"),
        ("Restwert aus EKET/EKPO-Sample", "remaining value from EKET/EKPO sample"),
        ("EKKO live, Terminwerte fehlen noch", "EKKO live, schedule values still missing"),
        ("aktive Lieferanten mit Spend-Positionen", "active suppliers with spend items"),
        ("Zeitfilter und Verlauf", "Time filter and trend"),
        ("Spend und Performance pro Lieferant", "Spend and performance by supplier"),
        ("Spend nach Warengruppe", "Spend by material group"),
        ("Artikel- und Preisentwicklung", "Article and price development"),
        ("Regionale Spend-Verteilung", "Regional spend distribution"),
        ("Bestellkopf wartet auf SAP", "Purchase header is waiting for SAP"),
        ("Anzahl Bestellpositionen im Zeitraum", "Number of order items in period"),
        ("Spend und offene Werte bleiben Simulation", "Spend and open values remain simulation"),
        ("Anzahl Termineinteilungen im Zeitraum", "Number of schedule lines in period"),
        ("Faelligkeiten und Kontrakte warten auf SAP", "Due dates and contracts wait for SAP"),
        ("Livewerte, Simulation und 3D-Analyse werden getrennt ausgewiesen", "Live values, simulation and 3D analysis are shown separately"),
        ("aus SAP Positionen", "from SAP item rows"),
        ("Simulation bis EKPO liefert", "simulation until EKPO delivers"),
        ("Matrix wie Excel/PowerBI", "matrix like Excel/Power BI"),
        ("Jahr, Lieferant, Warengruppe, Artikel", "year, supplier, material group, article"),
        ("EKPOSet fuer Spend notwendig", "EKPOSet required for spend"),
        ("mit nicht geloeschten Positionen", "with non-deleted items"),
        ("aus SAP Terminen/Positionen", "from SAP schedules/items"),
        ("Simulation bis EKET liefert", "simulation until EKET delivers"),
        ("aus SAP Terminen", "from SAP schedules"),
        ("aus SAP Einteilungen", "from SAP schedules"),
        ("EKET-Probe", "EKET sample"),
        ("Lieferant / Artikel / Monat", "supplier / article / month"),
        ("letztes bekanntes EKKO-Datum", "latest known EKKO date"),
        ("mit nicht geloeschten EKPO-Positionen", "with non-deleted EKPO items"),
        ("Bewertungsdaten (EKBE/QM) nicht angebunden", "rating data (EKBE/QM) not connected"),
        ("Netwr CHF/Stk braucht EKPO", "Netwr CHF/unit needs EKPO"),
        ("Reklamationsquelle noch nicht angebunden", "claim source not connected yet"),
        ("berechenbar", "calculable"),
        ("wartet auf EKPO/EKET", "waiting for EKPO/EKET"),
        ("teilweise", "partial"),
        ("wartet auf EKET", "waiting for EKET"),
        ("wartet auf EKPO", "waiting for EKPO"),
        ("Wartet auf SAP", "Waiting for SAP"),
        ("als Detail verfuegbar", "available as detail"),
        ("offener Wert", "open value"),
        ("kurzfristig faellig", "due short-term"),
        ("offene Mengen", "open quantities"),
        ("Top nach Spend", "top by spend"),
        ("> +2% ggue. Vorjahr", "> +2% vs. prior year"),
        ("Lieferanten-Pareto", "supplier pareto"),
        ("vom Gesamtspend", "of total spend"),
        ("Spend netto", "net spend"),
        ("Pflichtfelder", "required fields"),
        ("Cache-Zeilen", "cache rows"),
        ("Positionen", "items"),
        ("Bestellkoepfe", "headers"),
        ("Liefertermin-Risiko produktiv", "Delivery due-date risk productive"),
        ("Preisentwicklung CHF produktiv", "Price trend CHF productive"),
        ("Spend-Konzentration produktiv", "Spend concentration productive"),
        ("Datenqualitaet produktiv", "Data quality productive"),
        ("Einkauf Analyse", "Purchasing analysis"),
        ("Offene EKET-Mengen werden bewertet und nach Faelligkeit, Lieferant und Artikel priorisiert.", "Open EKET quantities are valued and prioritised by due date, supplier and article."),
        ("Netto-Stueckpreise werden wie in PowerBI als Minimum je Artikel und Jahr gezeigt.", "Net unit prices are shown like in Power BI as minimum by article and year."),
        ("Lieferantenspend wird als Pareto ausgewertet, um Abhaengigkeit und Buendelungspotenzial zu zeigen.", "Supplier spend is evaluated as pareto to show dependency and bundling potential."),
        ("Pflichtfelder und Nullwerte im Einkauf-Cache werden als Qualitaetsampel gezaehlt.", "Required fields and zero values in the purchasing cache are counted as quality indicators."),
        ("Echte Analyse aus dem Einkauf-Cache.", "Real analysis from the purchasing cache."),
        ("Offener Wert nach Faelligkeit", "Open value by due date"),
        ("Min. Stueckpreis nach Jahr", "Min. unit price by year"),
        ("Top Lieferanten Spend", "Top supplier spend"),
        ("Datenqualitaetsfehler", "Data quality issues"),
        ("Beschaffungsregion", "Procurement region"),
        ("Waehrung", "Currency"),
        ("Material", "Material"),
        ("Waehrung des Bestellbelegs (EKKO-Waers). Balken und erster Betrag sind nach CHF bewertet, damit die Waehrungen vergleichbar sind; in Klammern die Summe in der Belegwaehrung selbst (das tatsaechliche Waehrungsexposure). NICHT die Beschaffungsregion: ein Schweizer Lieferant kann in EUR fakturieren.", "Currency of the purchase order (EKKO Waers). Bars and the first amount are valued in CHF so the currencies are comparable; in brackets the sum in the document currency itself (the actual currency exposure). NOT the procurement region: a Swiss supplier can invoice in EUR."),
        ("Beschaffungsregion = Land des Lieferanten (LFA1-Land1), ueber den Bestellbeleg zugeordnet. Zeigt den CHF-Spend je Lieferantenland im gewaehlten Zeitraum.", "Procurement region = supplier country (LFA1 Land1), assigned via the purchase order. Shows CHF spend by supplier country in the selected period."),
        ("Warengruppe aus dem Materialstamm (MARA-MATKL), Fallback Beleg-Warengruppe (EKPO.Matkl). Texte aus dem SAP-Export T023T; unbekannte Codes zeigen den reinen Code. \"01\" ist die SAP-Sammelgruppe \"Dummy\" fuer unklassifizierte Altbestaende.", "Material group from the material master (MARA-MATKL), fallback to the document material group (EKPO.Matkl). Texts from the SAP export T023T; unknown codes show the bare code. \"01\" is SAP's catch-all group \"Dummy\" for unclassified legacy stock."),
        ("Stammdaten nachpflegen; ohne beide Klassen ist keine belastbare Beschaffungsstrategie ableitbar.", "Complete master data; without both classes no reliable procurement strategy can be derived."),
        ("Strategisch absichern: Rahmenvertrag, Lieferfaehigkeit und automatische Disposition pruefen.", "Secure strategically: review framework agreement, supply capability and automated planning."),
        ("Versorgungsrisiko priorisieren: Forecast, Sicherheitsbestand und Zweitquelle pruefen.", "Prioritize supply risk: review forecast, safety stock and a second source."),
        ("Standardisieren und Mengen buendeln; Bestellrhythmus und Konditionen optimieren.", "Standardize and bundle volumes; optimize order cadence and terms."),
        ("Losgroessen, Mindestmengen und schwankende Bedarfsursachen mit dem Disponenten pruefen.", "Review lot sizes, minimum quantities and volatile demand drivers with the planner."),
        ("Prozesskosten senken: Katalog, Automatisierung und Sammelbestellungen pruefen.", "Reduce process cost: review catalog, automation and consolidated orders."),
        ("Tail Spend reduzieren: buendeln, auslisten oder auf Standardalternativen umstellen.", "Reduce tail spend: bundle, phase out or switch to standard alternatives."),
        ("Klassifikation fachlich pruefen und anschliessend einer Beschaffungsstrategie zuordnen.", "Validate the classification and then assign a procurement strategy.")
    ];
}
