SELECT COUNT(*) AS TOTAL, MIN(j."DueDate") AS MIN_DUE, MAX(j."DueDate") AS MAX_DUE,
 SUM(CASE WHEN j."DueDate"<>h."DueDate" THEN 1 ELSE 0 END) AS LINE_DIFFERS_FROM_HEADER,
 SUM(CASE WHEN j."DueDate"<>h."RefDate" THEN 1 ELSE 0 END) AS DUE_DIFFERS_FROM_POSTING,
 SUM(CASE WHEN j."MthDate" IS NOT NULL THEN 1 ELSE 0 END) AS MATCH_DATE_FILLED,
 SUM(CASE WHEN j."BalDueDeb"<>0 OR j."BalDueCred"<>0 THEN 1 ELSE 0 END) AS BALANCE_DUE_NONZERO
FROM "{schema}"."JDT1" j INNER JOIN "{schema}"."OJDT" h ON j."TransId"=h."TransId"
WHERE h."RefDate">=DATE'2025-01-01'
;;
SELECT "Canceled", COUNT(*) AS TOTAL, MIN("ReconDate") AS MIN_RECON, MAX("ReconDate") AS MAX_RECON
FROM "{schema}"."OITR" GROUP BY "Canceled"
